apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-image-from-git-source-tr
spec:
  serviceAccountName: dockerhub-service
  taskRef:
    name: build-sampleapp-from-git
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: sampleapp-pull-from-git 
    outputs:
      - name: builtImage
        resourceRef:
          name: sampleapp-img-tohub
