apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: sampleapp-pull-from-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/dominicpg/nginx-world.git
